### ISSUE TITLE
Does not work on M1 Macs

### ISSUE THREAD

**Issue by fancyham** [plainlab/plainmerge#1]
Cannot run on an M1 Mac on Big Sur — incompatible application.  

(I downloaded the 0.0.6 Mac DMG)

**Comment by manhtai** [comment]
I've released a new version with ARM support https://github.com/plainlab/plainmerge/releases/tag/v0.0.7

For M1 please use `PlainMerge-0.0.7-arm64.dmg` and let me know if it works on your Mac.

**Comment by fancyham** [comment]
Got it working on the M1 mac — thank you.  Nice.

Suggest you name the installer M1 as Arm64 could also be a Windows or Linux machine, or make it a Universal Intel+M1 build.
