### ISSUE TITLE
Can't output PDFs consistently

### ISSUE THREAD

**Issue by fancyham** [plainlab/plainmerge#6]
I haven't been able to output PDFs consistently.  I was able to output a single PDF which had the correct fields filled out, but   otherwise, haven't been able to.

M1 Mac on Big Sur 11.5.2

**Comment by manhtai** [comment]
Did you choose to export 1 or many PDFs? I got no problem with my the test files. Please recheck you Excel file to make sure. Other than that I have no clue.

Maybe next version will have some kind of error report to give us something 🤖

**Comment by fancyham** [comment]
I think it may be a bad PDF on my end.  Perhaps something to do with Apple Preview having edited the document before but I think there may be some internal errors, perhaps with a 'font'.

I'm using SBA Form 641 which is available from https://www.sba.gov/sites/default/files/2018-09/SBA%20Form%20641_48_Final%20%281%29_0.pdf, but my bad PDF looks like it was altered before I got it.

**Comment by fancyham** [comment]
I did get it to work properly with other PDF files.  With my (likely bad) PDF, it wouldn't preview at all.  Since this seemed to be user / input error, closing the issue. :)

Yes, error reports would be nice — perhaps even just to console.
